---
title: "PolyJIT Single Experiment"
author: "Andreas Simbürger"
date: "April 27, 2016"
output:
  html_document:
    css: pjit-experiments.css
    fig_caption: yes
    fig_height: 16
    fig_width: 16
    highlight: pygments
    number_sections: yes
    theme: null
    toc: yes
params:
  experiment: "73d220af-c6fa-4e9e-b68a-2d58a2329c1c"
  groups: [polybench, pprof, lnt]
---


```{r test, echo=FALSE, include=FALSE}
# Set defaults for interactive R debug sessions.
devtools::load_all()
library(RPostgres)
library(DT)
library(gridExtra)
library(ggplot2)
if (!require(reshape2)) { install.packages("reshape2") }
library(reshape2)
if (!require(rpivotTable)) { install.packages("rpivotTable")}
library(rpivotTable)

if (is.null(params)) {
  params <- list()
  params$groups <- c('polybench', 'pprof', 'lnt')
  params$experiment == "73d220af-c6fa-4e9e-b68a-2d58a2329c1c"
  message("Using defaults, interactive session.")
}

c <- pprof::login()
exps <- pprof::get_experiments(c)

plots_for_baseline <- function(baselines) {
  experiments_from_db <- exps[exps$name %in% baselines,]
  plots <- apply(experiments_from_db, 1, function(elem, db, all_exps) {
    baseline <- elem[2]
    experiment <- params$experiment
    eobj <- all_exps[all_exps$id == experiment,]
    speed <- sql.get(c, query_speedup_no_papi('', baseline, experiment))
    
    if (length(unique(speed$project_name)) > 30) {
      p <- ggplot(data = speed, aes(x = project_name, y = speedup_corrected, fill = factor(cores))) +
        geom_bar(stat="identity", position = "dodge") +
        theme(axis.text = element_text(size = 8), axis.text.x = element_text(angle = 45, hjust = 1),
              legend.position="none") +
        labs(title = paste(elem[3], "[", elem[1],"] vs. ",
                           eobj$description, "[", eobj$name, "]"))
      print(p)
    }
  }, db, experiments_from_db)
}
```


# Experiment configuration

```{r metadata, echo=FALSE}
```

# Speedup over all PolyJIT enabled run-time measurements

```{r baseline, echo=FALSE, message=FALSE}
plots_for_baseline(c('pj-raw'))
```
